In [9]:
#Import the numpy file
import numpy as np

# Create a random 5x5 ndarray
X = np.random.rand(5, 5)

# Calculate the mean and standard deviation of the ndarray
mean_X = X.mean()
std_X = X.std()

# Normalize the ndarray
X_normal = (X - mean_X) / std_X

# Save the normalized ndarray to a file
np.save('X_normalized.npy', X_normal)

#Example Output:
print("Original ndarray:")
print(X)
print("\nNormalized ndarray:")
print(X_normal)

Original ndarray:
[[0.6519209  0.32208888 0.26351102 0.48537945 0.10145817]
 [0.38849013 0.09089227 0.06008886 0.83025871 0.94834552]
 [0.31662079 0.5928241  0.81274523 0.44333557 0.25893147]
 [0.89221795 0.24531984 0.12102289 0.0941334  0.47096847]
 [0.94837712 0.69666637 0.23504056 0.98867808 0.1935909 ]]

Normalized ndarray:
[[ 0.64158973 -0.45031832 -0.64424014  0.0902547  -1.18071569]
 [-0.23049715 -1.21569407 -1.31766868  1.23197658  1.62290265]
 [-0.46842039  0.44594993  1.17399825 -0.04893145 -0.65940074]
 [ 1.43709249 -0.70446201 -1.11594674 -1.20496433  0.04254719]
 [ 1.62300728  0.7897195  -0.73849155  1.75642349 -0.87571052]]


In [3]:
#Import the numpy file
import numpy as np

# Create a 10x10 ndarray of squares of the first 100 positive integers
A = (np.arange(1, 101) ** 2).reshape(10, 10)

# Find the elements that are divisible by 3
div_by_3 = A[A % 3 == 0]

# Save the result to a file
np.save('div_by_3.npy', div_by_3)

#Example Output
print("Original ndarray:")
print(A)
print("\nElements divisible by 3:")
print(div_by_3)

Original ndarray:
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3:
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
