In [7]:
#Import the numpy file
import numpy as np

# Create a random 5x5 ndarray
X = np.random.rand(5, 5)

# Calculate the mean and standard deviation of the ndarray
mean_X = X.mean()
std_X = X.std()

# Normalize the ndarray
X_normal = (X - mean_X) / std_X

# Save the normalized ndarray to a file
np.save('X_normalized.npy', X_normal)

#Example Output:
print("Original ndarray:")
print(X)
print("\nNormalized ndarray:")
print(X_normal)

Original ndarray:
[[0.84114283 0.61615704 0.42682067 0.09392126 0.97843089]
 [0.48268701 0.17691994 0.96319695 0.57681276 0.60477989]
 [0.79325795 0.18443667 0.34954193 0.7980681  0.36716204]
 [0.543309   0.75115182 0.95363471 0.03192089 0.94239902]
 [0.03879343 0.06304986 0.76406417 0.44698926 0.81703505]]

Normalized ndarray:
[[ 0.95965501  0.23248268 -0.37946783 -1.45542574  1.40338115]
 [-0.1989033  -1.18716729  1.35414382  0.10531877  0.19571082]
 [ 0.8048872  -1.1628726  -0.629239    0.82043398 -0.57228937]
 [-0.00296809  0.66879677  1.32323789 -1.65581598  1.28692322]
 [-1.63360337 -1.55520462  0.71053051 -0.31428133  0.88173669]]
